import "./style.css"

export default function backstroyPage() {
    return (
        <main>
            <div className="backstory-section">
                <h2>The History of Raven's Oath</h2>
                <p id="backstoryTxt">
                    In the misty fjords of northern Scandinavia, the Ravens Oath clan thrived, forged from the legacy of the legendary warrior Bjorn Ravenscar. Once a mere warrior seeking knowledge through battle, Bjorn had been blessed by Odin after surviving a fierce confrontation. In that moment, he vowed to seek wisdom through strength, and his oath became the guiding principle of his clan. The clan’s emblem, two black ravens with outstretched wings, symbolized Odin’s wisdom and the pursuit of knowledge. Each member carried Bjorn's spirit, learning from every battle, whether victorious or not. Under the glow of the full moon, they gathered for the Althing, sharing tales of past skirmishes and strategies, passing wisdom down through generations. Young warriors faced the Raven's Trial, venturing into the wild, returning with a raven's feather to signify their readiness. As they raided neighboring settlements, the Ravens Oath gathered not just riches but stories, techniques, and tools that expanded their understanding. Known for their cunning tactics, they often outsmarted larger foes. This hunger for knowledge earned them both respect and enmity among other clans. Their legendary figures included Astrid the Seer, whose visions guided their path, and Ragnar Ironhand, whose unconventional strategies turned the tide in many battles. Notable conflicts like the Battle of Stone Hill and the Siege of Frostholm became part of their storied history, each teaching them valuable lessons. Beyond raiding, the clan set their sights on distant lands, embarking on voyages that took them far from home. With their swift longships, they charted coastlines and rivers, mapping the world as they went. Each expedition was a quest for knowledge, where they engaged with various cultures, exchanging ideas and learning from one another. They believed that true strength lay not just in combat but in the bonds forged through shared experiences. Their travels birthed legends—tales of fierce encounters and diplomatic exchanges that showcased their adaptability and respect for diverse cultures. As they continued their journeys, the Ravens Oath envisioned a future of unity, aspiring to build a network of allies while collecting the wisdom of the world. Through the lessons of battle, the honor of fallen warriors, and the knowledge gained on distant shores, the Ravens Oath clan solidified their legacy as both fierce fighters and wise seekers of understanding. 
                </p>
            </div>
        </main>
    )
}